name: update-rss-feed
on: [push]
jobs:
  update-rss-feed:
    runs-on: ubuntu-latest
    steps:
      - name: Setup checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Create .env
        run: |
          touch .env
          echo "TEAMS_HOOK_URL=${{ secrets.TEAMS_HOOK_URL }}" >> .env
      - name: Post to teams
        run: | 
          yarn
          yarn start     
